### ISSUE TITLE
Fingerprint Sensor is not working correct

### ISSUE THREAD

**Issue by zipara** [iodeOS/ota#27] opened 2022-10-21 20:45 UTC
Hi,
the fingerprint sensor on my Samsung A5 is only working sometimes. I have tried different versions of iodé and did a reset of my fingerprint more than twice. Can you help me?

**Comment by vincentvidal** [comment] 2022-11-29 12:34
duplicate of https://gitlab.com/iode/ota/-/issues/85

**Closed by vincentvidal** 2022-11-29 12:34 UTC
